config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Evita ruído no log em desenvolvimento (Chrome/DevTools e alguns setups de SW)
  get '/service-worker', to: proc { [204, {}, []] }
  get '/.well-known/appspecific/com.chrome.devtools', to: proc { [204, {}, []] }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  authenticate :user do
    resources :clients
    resources :channels
    resources :devices
    root to: 'home#index'
    post '/others', to: 'home#others'
    get '/register_device', to: 'register_device#index'
    get '/info', to: 'home#info'
    get '/monitoring', to: 'monitoring#index'
  end

  post '/device_login',   to: 'iot#device_login'
  post '/mqtt_info',      to: 'iot#mqtt_info'
  post '/alertaTelegram', to: 'iot#telegram'
  post '/alertaWhatsApp', to: 'iot#whatsapp'
  post '/alertaEmail',    to: 'iot#email'
  post '/alertaSms',      to: 'iot#sms'
  post '/telegram_alert', to: 'iot#telegram_alert'
  post '/traccar_event_webhook', to: 'iot#traccar_event_webhook'
end

app/models/channel.rb
# frozen_string_literal: true

class Channel < ApplicationRecord
  validates :client_id, presence: true
  validates :device_id, presence: true
  validates :category, presence: true, length: { minimum: 3 }
  validates :path, presence: true, length: { minimum: 3 }

  def self.ransackable_attributes(_auth_object = nil)
    %w[array_info category client_id color created_at device_id id id_value label obs path platform previous_state
       range tipo updated_at]
  end
end

app/controllers/channels_controller.rb
# frozen_string_literal: true

class ChannelsController < AdminController
  before_action :set_channel, only: %i[show edit update destroy]

  def index
    @channels = Channel.all
  end

  def show; end

  def new
    @channel = Channel.new
  end

  def edit; end

  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to channel_url(@channel), notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to channel_url(@channel), notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end

  def channel_params
    params.require(:channel).permit(:category, :platform, :path, :tipo, :color, :range, :array_info, :label,
                                    :previous_state, :obs)
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channel.html.erb
<div id="<%= dom_id channel %>">

  <p>
    <strong>Category:</strong>
    <%= channel.client_id %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= channel.device_id %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= channel.category %>
  </p>

  <p>
    <strong>Platform:</strong>
    <%= channel.platform %>
  </p>

  <p>
    <strong>Path:</strong>
    <%= channel.path %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= channel.tipo %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= channel.color %>
  </p>

  <p>
    <strong>Range:</strong>
    <%= channel.range %>
  </p>

  <p>
    <strong>Array info:</strong>
    <%= channel.array_info %>
  </p>

  <p>
    <strong>Label:</strong>
    <%= channel.label %>
  </p>

  <p>
    <strong>Previous state:</strong>
    <%= channel.previous_state %>
  </p>

  <p>
    <strong>Obs:</strong>
    <%= channel.obs %>
  </p>

</div>

app/views/channels/_form.html.erb
<%= form_with(model: channel) do |form| %>
  <% if channel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.label :device_id, style: "display: block" %>
    <%= form.text_field :device_id %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :platform, style: "display: block" %>
    <%= form.text_field :platform %>
  </div>

  <div>
    <%= form.label :path, style: "display: block" %>
    <%= form.text_field :path %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.text_field :tipo %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :range, style: "display: block" %>
    <%= form.text_field :range %>
  </div>

  <div>
    <%= form.label :array_info, style: "display: block" %>
    <%= form.text_field :array_info %>
  </div>

  <div>
    <%= form.label :label, style: "display: block" %>
    <%= form.text_field :label %>
  </div>

  <div>
    <%= form.label :previous_state, style: "display: block" %>
    <%= form.text_field :previous_state %>
  </div>

  <div>
    <%= form.label :obs, style: "display: block" %>
    <%= form.text_field :obs %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render "form", channel: @channel %>

<br>

<div>
  <%= link_to "Show this channel", @channel %> |
  <%= link_to "Back to channels", channels_path %>
</div>

app/views/channels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Channels</h1>

<div id="channels">
  <% @channels.each do |channel| %>
    <%= render channel %>
    <p>
      <%= link_to "Show this channel", channel %>
    </p>
  <% end %>
</div>

<%= link_to "New channel", new_channel_path %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render "form", channel: @channel %>

<br>

<div>
  <%= link_to "Back to channels", channels_path %>
</div>

app/views/channels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @channel %>

<div>
  <%= link_to "Edit this channel", edit_channel_path(@channel) %> |
  <%= link_to "Back to channels", channels_path %>

  <%= button_to "Destroy this channel", @channel, method: :delete %>
</div>