config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Evita ruído no log em desenvolvimento (Chrome/DevTools e alguns setups de SW)
  get '/service-worker', to: proc { [204, {}, []] }
  get '/.well-known/appspecific/com.chrome.devtools', to: proc { [204, {}, []] }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  authenticate :user do
    resources :clients
    resources :channels
    resources :devices
    root to: 'home#index'
    post '/others', to: 'home#others'
    get '/register_device', to: 'register_device#index'
    get '/info', to: 'home#info'
    get '/monitoring', to: 'monitoring#index'
  end

  post '/device_login',   to: 'iot#device_login'
  post '/mqtt_info',      to: 'iot#mqtt_info'
  post '/alertaTelegram', to: 'iot#telegram'
  post '/alertaWhatsApp', to: 'iot#whatsapp'
  post '/alertaEmail',    to: 'iot#email'
  post '/alertaSms',      to: 'iot#sms'
  post '/telegram_alert', to: 'iot#telegram_alert'
  post '/traccar_event_webhook', to: 'iot#traccar_event_webhook'
end

app/models/device.rb
# frozen_string_literal: true

class Device < ApplicationRecord
  # belongs_to :client
  # has_many :channels, dependent: :destroy

  validates :description, presence: true, length: { minimum: 3 }
  validates :device, presence: true, length: { minimum: 3 }
  validates :token, presence: true, length: { minimum: 5 }, uniqueness: { case_sensitive: false }
  validates :pathUpdate, presence: true, length: { minimum: 10 }

  def self.ransackable_attributes(_auth_object = nil)
    %w[client_id created_at description device id linkAjuda obs pathUpdate tipo token updated_at versao configs devedor last_offline]
  end
end

app/controllers/devices_controller.rb
# frozen_string_literal: true

class DevicesController < AdminController
  before_action :set_device, only: %i[show edit update destroy]

  def index
    @devices = Device.all
  end

  def show; end

  def new
    @device = Device.new
  end

  def edit; end

  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to device_url(@device), notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to device_url(@device), notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:description, :device, :token, :tipo, :versao, :linkAjuda, :pathUpdate, :obs, :client_id)
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_device.html.erb
<div id="<%= dom_id device %>">
  <p>
    <strong>Description:</strong>
    <%= device.description %>
  </p>

  <p>
    <strong>Device:</strong>
    <%= device.device %>
  </p>

  <p>
    <strong>Token:</strong>
    <%= device.token %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= device.tipo %>
  </p>

  <p>
    <strong>Versao:</strong>
    <%= device.versao %>
  </p>

  <p>
    <strong>Linkajuda:</strong>
    <%= device.linkAjuda %>
  </p>

  <p>
    <strong>Pathupdate:</strong>
    <%= device.pathUpdate %>
  </p>

  <p>
    <strong>Obs:</strong>
    <%= device.obs %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= device.client_id %>
  </p>

</div>

app/views/devices/_form.html.erb
<%= form_with(model: device) do |form| %>
  <% if device.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
        <% device.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :device, style: "display: block" %>
    <%= form.text_field :device %>
  </div>

  <div>
    <%= form.label :token, style: "display: block" %>
    <%= form.text_field :token %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.text_field :tipo %>
  </div>

  <div>
    <%= form.label :versao, style: "display: block" %>
    <%= form.text_field :versao %>
  </div>

  <div>
    <%= form.label :linkAjuda, style: "display: block" %>
    <%= form.text_field :linkAjuda %>
  </div>

  <div>
    <%= form.label :pathUpdate, style: "display: block" %>
    <%= form.text_field :pathUpdate %>
  </div>

  <div>
    <%= form.label :obs, style: "display: block" %>
    <%= form.text_field :obs %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render "form", device: @device %>

<br>

<div>
  <%= link_to "Show this device", @device %> |
  <%= link_to "Back to devices", devices_path %>
</div>

app/views/devices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Devices</h1>

<div id="devices">
  <% @devices.each do |device| %>
    <%= render device %>
    <p>
      <%= link_to "Show this device", device %>
    </p>
  <% end %>
</div>

<%= link_to "New device", new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render "form", device: @device %>

<br>

<div>
  <%= link_to "Back to devices", devices_path %>
</div>

app/views/devices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @device %>

<div>
  <%= link_to "Edit this device", edit_device_path(@device) %> |
  <%= link_to "Back to devices", devices_path %>

  <%= button_to "Destroy this device", @device, method: :delete %>
</div>