config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Evita ruído no log em desenvolvimento (Chrome/DevTools e alguns setups de SW)
  get '/service-worker', to: proc { [204, {}, []] }
  get '/.well-known/appspecific/com.chrome.devtools', to: proc { [204, {}, []] }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  authenticate :user do
    resources :clients
    resources :channels
    resources :devices
    root to: 'home#index'
    post '/others', to: 'home#others'
    get '/register_device', to: 'register_device#index'
    get '/info', to: 'home#info'
    get '/monitoring', to: 'monitoring#index'
  end

  post '/device_login',   to: 'iot#device_login'
  post '/mqtt_info',      to: 'iot#mqtt_info'
  post '/alertaTelegram', to: 'iot#telegram'
  post '/alertaWhatsApp', to: 'iot#whatsapp'
  post '/alertaEmail',    to: 'iot#email'
  post '/alertaSms',      to: 'iot#sms'
  post '/telegram_alert', to: 'iot#telegram_alert'
  post '/traccar_event_webhook', to: 'iot#traccar_event_webhook'
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  # has_many :devices, dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    %w[address_mqtt cel created_at email id id_value name obs updated_at]
  end
end

app/controllers/clients_controller.rb
class ClientsController < AdminController
  before_action :set_client, only: %i[show edit update destroy]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show; end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit; end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy!

    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def client_params
    params.require(:client).permit(:name, :email, :cel, :address_mqtt, :obs)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

  <p>
    <strong>Cel:</strong>
    <%= client.cel %>
  </p>

  <p>
    <strong>Address mqtt:</strong>
    <%= client.address_mqtt %>
  </p>

  <p>
    <strong>Obs:</strong>
    <%= client.obs %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :cel, style: "display: block" %>
    <%= form.text_field :cel %>
  </div>

  <div>
    <%= form.label :address_mqtt, style: "display: block" %>
    <%= form.text_field :address_mqtt %>
  </div>

  <div>
    <%= form.label :obs, style: "display: block" %>
    <%= form.text_field :obs %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Show this client", client %>
    </p>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>